### ISSUE TITLE
Creating activity for workouts with heartbeat rate

### ISSUE THREAD

**Issue by saroshaga** [UnbounDev/node-strava-v3#104]
I'm trying to pull workout data from my FitBit and upload to Strava. Have to do this because, the official Strava-FitBit integration does not sync non-GPS related activities.

Is there a way to create an activity with the heartbeat rate?

The allowed list of parameters for creating an activity doesn't seem to include any such field.

**Comment by markstos** [comment]
You should refer to the official Strava documentation. If you'd like to improve the documentation of this module, please submit a pull request.

**Comment by saroshaga** [comment]
thanks!
