### ISSUE TITLE
Using `await` on API calls not working

### ISSUE THREAD

**Issue by jeremylivingston** [UnbounDev/node-strava-v3#105]
I'm not sure if I'm doing something wrong, but I am unable to get the `await` keyword to work as expected on API calls. Code is listed below, which is also how the docs show calls to the Promise API:

```
const strava = require('strava-v3')
const payload = await strava.athlete.get({})
console.log(payload)
```

Error received:
```
const payload = await strava.athlete.get({})
                ^^^^^

SyntaxError: await is only valid in async function
```

Does this syntax actually work for these calls? I noticed that none of the functions are declared as `async`. Am I doing something wrong or should I be calling this endpoint differently? Thanks for the help!

**Comment by markstos** [comment]
Looks like you are trying to use `await` at the top level or in a non async function, which is an issue with your code,  not ours.

**Comment by jeremylivingston** [comment]
@markstos Do you have an example of how this should be done instead? I pulled the above code straight from the documentation, so it seems that if this isn't the proper usage that there should be an update to the README.

**Comment by markstos** [comment]
@jeremylivingston How to use `await` properly is not specific to this project and is outside of the scope of our documentation. 

The error message provides a strong hint about what to do: make the `await` call inside of an `async` function.

**Comment by jeremylivingston** [comment]
@markstos Thanks for the insightful response! I'd suggest updating your documentation if you're not willing to provide guidance on how to properly use the library since the examples provided don't work.

**Comment by jeremylivingston** [comment]
@markstos Will do!
