### ISSUE TITLE
Route file download support

### ISSUE THREAD

**Issue by pelmers** [UnbounDev/node-strava-v3#107]
It would be great if this library supported the strava route export endpoint (http://developers.strava.com/docs/reference/#api-Routes).

I see https://github.com/UnbounDev/node-strava-v3/pull/78 was made a while ago, is there any current plan to update this work to the latest version?

**Comment by edilson** [comment]
Hi @markstos, I have added this in the #121

**Comment by markstos** [comment]
Released in 2.1 today, thanks to @edilson
