### ISSUE TITLE
Allow non-default configuration location

### ISSUE THREAD

**Issue by curtisr7** [UnbounDev/node-strava-v3#12]
I'd like to have the ability to pass my API configuration rather than putting it in `[app-root]/data/strava_config` or env properties. 

Ideally I would like to be able to pass a configuration object to the API. That would allow me to parse the configuration however I want and not have to add to my ever growing list of env props. If this is something that seems reasonable I can spend some time to create / submit a PR?

**Comment by UnbounDev** [comment]
@curtisr7 absolutely! Submit a PR allowing for that enhancement and I will happily merge it in.

**Comment by Jakobud** [comment]
Yeah, you should never ever expect people to make edits to files in the `node_modules` folder. You should just allow the config variables to be set in the application, whether or not they are environment variables.

**Comment by UnbounDev** [comment]
The location is relative to your projects root directory (the modules `data/` dir is provided for reference), but I agree this ought to be configurable according to the developers wishes.

**Comment by HyperSprite** [comment]
I ran into this today, my dir structure has node_modules two levels up from my server.js. I also already had a config file that was imported into my server.js file for such things. What I ended up doing was adding the following in my server.js file which still allows the options on the command line (it's a bit ugly but it works fine):

```js
process.env.STRAVA_ACCESS_TOKEN = process.env.STRAVA_ACCESS_TOKEN || undefined;
process.env.STRAVA_CLIENT_ID = process.env.STRAVA_CLIENT_ID || config.stravaLogin.clientID;
process.env.STRAVA_CLIENT_SECRET = process.env.STRAVA_CLIENT_SECRET || config.stravaLogin.clientSecret;
process.env.STRAVA_REDIRECT_URI = process.env.STRAVA_REDIRECT_URI || config.stravaLogin.redirectURI;
```

For example, my config.js file looks like this:
```js
module.exports = {
  stravaLogin: {
    clientID: 'YOUR_STRAVA_CLIENT_ID',
    clientSecret: 'YOUR_STRAVA_CLIENT_SECRET',
    redirectURI: 'auth/strava',
  },
};
```

> Note: I also found if I did not pass  ```undefined``` to ```process.env.STRAVA_ACCESS_TOKEN```, it would complain about needing an access token.

Figured this might help the next person.
Cheers

**Comment by markstos** [comment]
Closing in favor of #50, #55
