### ISSUE TITLE
Problem with listing athlete activities after the date

### ISSUE THREAD

**Issue by sladkovm** [UnbounDev/node-strava-v3#14]
Hi,

I'm trying to fetch the athlete activities only after the certain date. I've read the Strava-v3 API and have added the *after* argument to the Strava server call:

```
var after = moment(afterDate)._d.getTime(); // returns seconds since UNIX epoch
strava.athlete.listActivities({'access_token':STRAVA_ACCESS_TOKEN, 
                                            id:STRAVA_CLIENT_ID, 
                                            after: after}, 
                                            callBack)
```

Without the *after* argument it fetches the latest 30 or so activities, while with *after* specified i do get the following error on the server:

```
{ message: 'Bad Request', errors: [ { resource: 'Application', field: 'after', code: 'future' } ] }
```

I'm running all this under the Meteor.js with all calls done on the server. Any thoughts on how to pass the *after* argument?

**Comment by UnbounDev** [comment]
Hey @sladkovm - that is exactly how you'd pass the arguments in, I've updated the [test code](https://github.com/UnbounDev/node-strava-v3/blob/master/test/athlete.js#L67-L86) to reflect that this is possible. That would imply that there is something else wrong w/ your query, I'd inspect the `after` variable; also, `id:STRAVA_CLIENT_ID` is incorrect as `id` ought to be the athlete id.
