### ISSUE TITLE
Several fields including `workout_type` cannot be set via the API wrapper

### ISSUE THREAD

**Issue by TimoSta** [UnbounDev/node-strava-v3#25]
I came across this because I tried to set the `workout_type` of my activities to _Race_ instead of _Run_, which is the default. While it is returned when reading an activity, currently it cannot be set using the create/update functionality.

While the docs do not explicitly state that this is a feature, I got a confirmation from one of the Strava API devs that this is indeed supported. In fact, all fields that can be read should be writeable via the API. (See  his answer below)

I think, we should extend the list of allowed fields for the create/update endpoints to reflect that. Any thoughts?

> Hi Timo,
> 
> Setting the workout_type is supported and appears to be working — I've just tried it on one of my own activities (see below for an example from the command-line using httpie and jq). Your application needs to have write access (see "access scopes" on http://strava.github.io/api/v3/oauth/).
> 
> ```
> $ http https://www.strava.com/api/v3/activities/595440342 'Authorization: Bearer <redacted>' | jq '.workout_type'
> 3
> $ http PUT https://www.strava.com/api/v3/activities/595440342 'Authorization: Bearer <redacted>' workout_type=1 | jq '.workout_type'
> 1
> ```
> 
> I'd be happy to update the documentation if you think this isn't something that is clear. I would generally expect the fields returned from a read request to also be updatable by the client.
> 
> Cheers,
> -j

**Comment by markstos** [comment]
This appears that it would be an easy patch:

https://github.com/UnbounDev/node-strava-v3/blob/master/lib/activities.js#L17

Please include a test if you can.
