### ISSUE TITLE
querystring.stringify in strava.oauth.getRequestAccessURL makes wrong redirectUrl

### ISSUE THREAD

**Issue by Keepertje** [UnbounDev/node-strava-v3#29]
Hai!
At first: thank you for the wonderful module!
I ran into a problem :
When calling  strava.oauth.getRequestAccessURL
it makes my redirect url of http://localhost:3000/index.html query.stringify() to http%3A%2F%2Flocalhost%3A3000%2Findex.html , which makes the accesUrl invalid.

**Comment by TimoSta** [comment]
Hi @Keepertje,
the library uses JavaScript's `encodeURIComponent()` internally to encode all URL parameters.

I just tried to reproduce the issue. Opening

    https://www.strava.com/oauth/authorize?client_id=XXXXX&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Findex.html&response_type=code&scope=view_private%2Cwrite

and authorizing the request correctly redirects to

    http://localhost:3000/index.html?state=&code=XXXXX

as expected.

Could you please add some additional details on how exactly you are using the function and where the problem occurs? Thanks!

-- Timo

**Comment by Keepertje** [comment]
I implemented the use of the strava API myself instead of using a package for it. So to reproduce, I have to go tback in my code for more than 6 months.
