### ISSUE TITLE
Authorization Errors with Premium Account

### ISSUE THREAD

**Issue by plondon** [UnbounDev/node-strava-v3#33]
Hi, thanks for the great node wrapper!

I'm trying to get access to my personal beacon's (http://strava.github.io/api/partner/v3/beacon/#beacon_status_get) by using utils.getEndpoint.

I have this so far:

```
app.get('/beacon', function (req, res) {
  console.log(req.query.code);
  return strava.oauth.getToken(req.query.code, function (err, payload) {
    if (err) res.send(err);
    return strava_util.getEndpoint('beacon/status', {'access_token': payload.access_token}, function (err, payload) {
      if (!err) res.send(payload);
      else res.send(err);
    });
  });
});
```

The req.query.code is the code returned by the `strava.oauth.getRequestAccessURL({scope:"view_private,write"});` url. 

The error I get when making the `beacon/status` GET request is:

```
{
  "message": "Authorization Error",
  "errors": [
    {
      "resource": "Application",
      "field": "beacon_access",
      "code": "missing"
    }
  ]
}
```

**Comment by martinconzelmann** [comment]
I am encountering the same problem with a simple HTTP-Request. 
https://www.strava.com/api/v3/beacon/status?access_token=28a4ffc17... 
results in 
{"message":"Authorization Error","errors":[{"resource":"Application","field":"beacon_access","code":"missing"}]}

What can we do to avoid this?

**Comment by TimoSta** [comment]
@plondon This seems to be a common issue with the authorization for the beacon endpoint. [This post in the Strava Google group](https://groups.google.com/d/msg/strava-api/2aw5t8dXEf8/aVlwZlO3BwAJ )describes the same problem. Unfortunately, the Strava devs didn't reply yet.

Also, the [Beacon API docs](http://strava.github.io/api/partner/v3/beacon/) seem to be down at the moment.

Are you still facing this issue? Is this still relevant for your project?

**Comment by plondon** [comment]
Hi @TimoSta thank you for replying! That was actually my post on the google group. Is this a problem you're experiencing as well?

**Comment by TimoSta** [comment]
No, just trying to get this project up and running again, working my way through all the open issues right now.

Are you able to access other private endpoints like your own detailed athlete info via `strava.athlete.get` with the token you generated? If so, this appears to be an issue with the authorization system of the Strava API.

This may be worth contacting the Strava devs about, their contact info is listed in the [support section](http://strava.github.io/api/partner/#support) of the docs. I don't have access to a premium account at the moment unfortunately, so I'm unable to reproduce the issue myself.

Please keep this thread updated in case you learn something new about this issue!

**Comment by M8inC** [comment]
I've got a reply via email from the strava devs some time ago. They siad, that the beacon-api ist NOT intended for public use and that it was a mistake to make it public in the API Docs. They are still discussing to open it for "non commercial users", but in the moment it ist only part of the Partner-API for commercial partners.

**Comment by plondon** [comment]
Thanks @M8inC, had I known this I'd never had created a premium account.
