### ISSUE TITLE
segments.listEfforts doesn't allow to filter by athlete_id

### ISSUE THREAD

**Issue by Vaudesir** [UnbounDev/node-strava-v3#4]
Hello,

It looks like segments.listEfforts doesn't allow to filter by athlete_id. I think this is because the _qsAllowedProps doesn't contain "athlete_id".
I've added it locally in the segments.js file in my local project and it seems to resolve the issue:
        //listSegments
        , 'athlete_id'
        , 'gender'
        , 'age_group'
        , 'weight_class'
        , 'following'
        , 'club_id'
        , 'date_range'

I'm not sure how to submit a proposed change, not having contributed on a project with GitHub before.

Thanks,

Laurent.

**Comment by UnbounDev** [comment]
Cool thanks for the fix! If you want the contributor credit, you can do the following:

1. Fork the project by selecting the 'fork' option in the upper right hand corner of [the repo page](https://github.com/UnbounDev/node-strava-v3).
2. Clone and edit your newly forked project.
3. Push to your cloned project w/ the fix.
4. From your cloned repo page, click the green button next to the branch name (if you hover over that button you'll see 'Compare, review, create pull request').

After that it's self explanatory, I'll get the notification and merge the changes! If you don't want to I'll just make the fix myself and push it.

**Comment by Vaudesir** [comment]
Oh great. Thanks for the help Austin! I will do this tonight.I really like the node-strava-v3 module.I'm using it on a web app I'm working on (just running on my localhost) to get some views (reporting) that the Strava web site is not giving me and, equally as important to me, to get some experience with Node, Express and Angular.
I'll push the change to my clone tonight.
Thanks again,
Laurent.
 


     On Monday, May 4, 2015 1:01 PM, Austin Brown <notifications@github.com> wrote:
   

 Cool thanks for the fix! If you want the contributor credit, you can do the following:   
   - Fork the project by selecting the 'fork' option in the upper right hand corner of the repo page.
   - Clone and edit your newly forked project.
   - Push to your cloned project w/ the fix.
   - From your cloned repo page, click the green button next to the branch name (if you hover over that button you'll see 'Compare, review, create pull request').
After that it's self explanatory, I'll get the notification and merge the changes! If you don't want to I'll just make the fix myself and push it.—

**Comment by UnbounDev** [comment]
No worries - glad you like that library, and thanks again for the fix!

Closed in 3ce083fc68b6426b366f82f9ae583c11f6c4d603.
