### ISSUE TITLE
Question on providing - getRequestAccessURL

### ISSUE THREAD

**Issue by alexellis** [UnbounDev/node-strava-v3#41]
Hi - what's the simplest / easiest endpoint that can be setup to provide an endpoint for "getRequestAccessURL"? What do you use?

Cheers,

Alex

**Comment by bryantee** [comment]
@alexellis 

I think `strava.oauth.getRequestAccessURL(args)` just returns a string representing the url to use to redirect the client for the initial oAuth handshake.

I just have an endpoint `'/token_exchange'` that I use to handle the redirect from Strava. Is that what you mean?

**Comment by F3L1X79** [comment]
I'm actually having trouble using the getRequestAcessURL endpoint:

```
var strava = require('strava-v3');
        strava.oauth.getRequestAccessURL({client_id: 'xxxxxx', response_type: 'code', redirect_uri: 'https://www.strava.com/oauth/authorize'}, function (err, payload, limits) {
            console.log('here');
            if (err) {
                return cb(err, null, null);
            } 
            cb(err, payload, limits);
        });
```

The word 'here' isn't displaying but it works great with `strava.athletes.get()` Endpoint. Any idea why?
