### ISSUE TITLE
Need information about rate limits

### ISSUE THREAD

**Issue by vlavrynovych** [UnbounDev/node-strava-v3#42]
It would be nice to have access to the response headers to get information about limits that described here: [rate-limiting](https://strava.github.io/api/#rate-limiting)

**Comment by vlavrynovych** [comment]
Hello @UnbounDev,

Did you have any chance to review this?
Here is my PR: https://github.com/UnbounDev/node-strava-v3/pull/43

**Comment by vlavrynovych** [comment]
Looks like this project does not maintained anymore. It's sad.

**Comment by TimoSta** [comment]
Since I really like this project and have use for it, I'd be willing to pick it up and take care of the open pull requests/general maintenance. It would be a shame to see it fall apart.

@UnbounDev What would you say to this?

**Comment by UnbounDev** [comment]
@TimoSta please do! I'm sad to say I've been unable to allocate any time to the upkeep of this repository, and would be happy to see additional contributors take over, if you can provide your npm username I'll add you as a collaborator w/ push access as well.

**Comment by TimoSta** [comment]
@UnbounDev My npm username is [@timosta](https://www.npmjs.com/~timosta).

**Comment by UnbounDev** [comment]
@TimoSta fyi:
```
$ npm access ls-collaborators strava-v3
{
  "unboundev": "read-write",
  "timosta": "read-write"
}
```

**Comment by vlavrynovych** [comment]
Resolved. Thank you @TimoSta!
