### ISSUE TITLE
wish: explicit configuration

### ISSUE THREAD

**Issue by markstos** [UnbounDev/node-strava-v3#50]
I'm interested in using this module in a large project that already has a centralized configuration system in place. Would there be willingness to accept a pull request that allows an explicit config to be loaded?

```javascript
    var strava = require('strava-v3');
    strava.fetchConfig(config)
    strava.athlete.get(...);
```

This would be implemented by exposing the existing authenticator/fetchConfig() method on the main object and updating it to accept an explicit config. If an explicit configuration was provided, it would be preferred over the other options.

The change would be backwards compatible. If an explicit configuration was *not* provided, the functionality would remain as before.

**Comment by TimoSta** [comment]
Hi @markstos,
I would love to see this feature in the library. In fact, it was requested before, see e.g. #12, but not implemented yet.

Feel free to submit a pull request for this, and I will gladly merge it.
-- Timo

**Comment by markstos** [comment]
Explicit configuration will be supported in the next release.
