### ISSUE TITLE
Previously deleted Activities not being detected at upload

### ISSUE THREAD

**Issue by OrganicPanda** [UnbounDev/node-strava-v3#6]
Hi There,

I notice that activities that I have deleted from Strava are not being detected in the same way that the web interface does:

![screen shot 2015-05-11 at 11 34 47](https://cloud.githubusercontent.com/assets/186071/7563112/e9bae214-f7d1-11e4-82dc-c10d18f54d9f.png)

The [API docs](http://strava.github.io/api/v3/uploads/#check-upload-status) say that 'The created activity has been deleted.' is a status but I'm wondering if maybe it doesn't work? Maybe this is a general API issue but I thought I would run it passed you first. 

This code does an upload, then delete then re-uploads the same file:

```js
var strava = require('strava-v3');

function upload(file, cb) {
  strava.uploads.post({
    data_type: 'fit',
    file: file,
    statusCallback: function(err, payload) {
      if (~payload.status.indexOf('still being processed')) return;

      cb(null, payload);
    }
  }, function(err, payload) {});
};

var file = '/Volumes/GARMIN/Garmin/Activities/2015-05-11-08-26-51.fit';

upload(file, function(err, upload1Payload) {
  if (err) return console.log('Error uploading Activity!', err);
  if (upload1Payload.error) {
    return console.log('Error uploading Activity!', upload1Payload.error);
  }

  console.log('Upload 1 success:', upload1Payload.status);

  strava.activities.delete({
    id: upload1Payload.activity_id
  }, function(err) {
    if (err) return console.log('Error deleting Activity 1!', err);

    console.log('Delete success!');

    upload(file, function(err, upload2Payload) {
      if (err) return console.log('Error uploading Activity 2!', err);
      if (upload2Payload.error) {
        return console.log('Error uploading Activity!', upload2Payload.error);
      }

      console.log('Upload 2 success:', upload2Payload.status);
    });
  });
});
```

I would expect something to fail or get a status indicating that the activity has previously deleted.

Edit: That outputs:

```shell
Upload 1 success: Your activity is ready.
Delete success!
Upload 2 success: Your activity is ready.
```

**Comment by UnbounDev** [comment]
@OrganicPanda the API status in question is the status of an activity *as it is being uploaded*. 

The code block you've posted actually does the following:

1. Create activity from upload.
2. Get id of activity from upload - call it `id_1`.
3. Delete activity `id_1`.
4. Create activity from upload. This new activity has a new id, call id `id_2`.

Now, if you were to delete `id_1` *while* it was being uploaded you should see the status indicating that the activity has been deleted.
