### ISSUE TITLE
Delete activity endpoint deprecated

### ISSUE THREAD

**Issue by OzQu** [UnbounDev/node-strava-v3#60]
Copy&Paste from the Strava API Changelog https://strava.github.io/api/v3/changelog/

"January 17, 2017 Removed delete activity endpoint"

This should probably be removed from the library also. I have not tested that does it still work and I don't actually know how deleting should be done in the future.

**Comment by markstos** [comment]
PR welcome.

**Comment by markstos** [comment]
This is being removed in the next release.
