### ISSUE TITLE
Get photos attribute un strava.athlete.listActivities(args,done) endpoint

### ISSUE THREAD

**Issue by F3L1X79** [UnbounDev/node-strava-v3#67]
As the title suggest is this possible?
The attribute "photos" clearly appears in the doc https://strava.github.io/api/v3/activities/ but I'm not able to get it even if I got photos on my activity. Do I miss something in the parameters, or do you forget a call somewhere?

**Comment by vlavrynovych** [comment]
Hello @F3L1X79,

As I remember when you try to get the list of activities you will receive a minimal info (see [docs](https://strava.github.io/api/v3/activities/#get-activities)). To get full information you should request them one by one separately.

**Comment by F3L1X79** [comment]
Hey, thank you for the answer! So if I understand correctly, the only way to retrieve photos is to loop on every activities with the strava.activities.listPhotos endpoint? Too bad :(

**Comment by vlavrynovych** [comment]
@F3L1X79,

Yes, I had same problem when tried to retrieve `device_name ` (which can be found in the list below).
See what I've found in the docs: 


> Summary representation attributes  
The summary representation of the activity object is the same as the detailed representation, except it does NOT include these attributes:
```
    calories
    description
    gear
    segment_efforts
    splits_metric
    splits_standard
    laps
    best_efforts
    device_name
    embed_token
    photos
```
> The map attribute also only includes a summary representation of the route.

**Comment by vlavrynovych** [comment]
And the worst part is that you have the request limits
Sad.

**Comment by F3L1X79** [comment]
Yea that's exactly the point. Thank you anyway!
