### ISSUE TITLE
return an object to all "get" functions so we can cancel them

### ISSUE THREAD

**Issue by brucem1976** [UnbounDev/node-strava-v3#70]
Would it be possible to return some sort of object reference to all "get" functions, so we can stop the get if need be? Like setTimeout or Tracker.autoRun allow - this will mean that it's possible to cancel upcoming get's from a componentWillUnmount lifecycle message, so that we don't get warnings when unmounted components are used in callbacks....

**Comment by markstos** [comment]
Once a request has been sent to Strava, you can't un-send it.

There are no plans to add a feature like this and no one else is has commented here to request it in over a year, so I'm closing this.

The workaround would be to wrap your `get` calls in something like `setTimeout()`.
