### ISSUE TITLE
segment explore endpoint

### ISSUE THREAD

**Issue by maxwell-oroark** [UnbounDev/node-strava-v3#81]
having trouble submitting the bounds argument when trying to use the `strava.segment.explore({
bounds: bbox
})` endpoint.

submitting an array bbox like the documenation states but it appears it's turning it into a network call with bounds query param multiple times.

```
https://www.strava.com/api/v3/segments/explore?bounds=29.356924207076137&bounds=-98.57250982841194&bounds=29.513394912212963&bounds=-98.39284677158804&activity_type=riding
```

**Comment by markstos** [comment]
You are welcome to submit a patch to our documentation to clarify that. I know a lot of our methods aren't documented, but it would be great to add the input data structures and output response formats.
