### ISSUE TITLE
strava.athlete.listActivities(args,done) rounds the lat and long values

### ISSUE THREAD

**Issue by cheesemacfly** [UnbounDev/node-strava-v3#9]
When I use `strava.athlete.listActivities(args,done)` it rounds the latitude and longitude values. For example, on my last activty, it should read `end_latlng: [40.823988,-73.944859]` and instead it reads `end_latlng: [ 40.82, -73.94 ]`. 

If it is of any help, I'm using Meteor and I have the same behavior calling the API directly with `Meteor.http` but it is very specific to the strava website. (I have a local copy of my data available through a Web API app and it works as expected)

**Comment by cheesemacfly** [comment]
This happens when the accessToken only allows public access.

**Comment by UnbounDev** [comment]
:+1: thanks for following through the issue and explaining the cause!
