### ISSUE TITLE
Correct import/require for TypeScript 

### ISSUE THREAD

**Issue by KyleGoslan** [UnbounDev/node-strava-v3#92]
I'm new to TS and trying to use this library with it. I can get everything working as per the documentation, but can't get it working with types.

**Comment by KyleGoslan** [comment]
Hey, @marcelotokarnia 

Looks great! I'll try implementing it on my project when I get a chance. Probably be a week or so before I get some time to work on it. 

Thanks!

**Comment by nik0kin** [comment]
The types were working for me with `import strava from 'strava-v3';`

with this tsconfig.json: 
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "declaration": true,
    "paths": {
      "*": [
        "node_modules/*",
      ]
    },
    "typeRoots": [
      "node_modules/@types",
      "index.d.ts",
    ],
    "strict": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    // "strictBindCallApply": true,
    "lib": [
      "es6"
    ]
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by markstos** [comment]
I'm about to push a new release with TypeScript-related improvements, so I'm closing this.
