### ISSUE TITLE
Missing Field activity:read_permission

### ISSUE THREAD

**Issue by JonasNicoletti** [UnbounDev/node-strava-v3#97]
Hello everyone,

I am missing the possibility to request an access_token with other scopes than _scope: read_ 
In my eyes it should be possible when requesting the token in [outh.getToken](https://github.com/UnbounDev/node-strava-v3/blob/5c52ed74671c20a9436ed234516e15b7f995fa22/lib/oauth.js#L46) to add an addition parameter where you can say for which scope you are asking the token. 
Do you think it is possible to add this feature? Otherwise how do you do  strava.athlete.listActivities without getting an 401 and this message ` {\"message\":\"Authorization Error\",\"errors\":[{\"resource\":\"AccessToken\",\"field\":\"activity:read_permission\",\"code\":\"missing\"}]}"`

**Comment by markstos** [comment]
scopes are requested in `oauth.getRequestAccessURL`, not `oauth.getToken()`. 

You can review our source code and also http://developers.strava.com/docs/authentication/
